spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5444/account_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
